In [1]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Fresh NewsGuard project path
PROJECT_ROOT = '/content/drive/MyDrive/NewsGuard'

# Verify project folder
print("\n📁 NewsGuard folder exists:", os.path.exists(PROJECT_ROOT))

if os.path.exists(PROJECT_ROOT):
    print("📂 Contents of NewsGuard:")
    for item in os.listdir(PROJECT_ROOT):
        print("   └──", item)
else:
    raise FileNotFoundError("❌ NewsGuard folder not found in Google Drive.")

print("\n✅ Drive mounted and NewsGuard folder verified.")

Mounted at /content/drive

📁 NewsGuard folder exists: True
📂 Contents of NewsGuard:
   └── archive (1).zip

✅ Drive mounted and NewsGuard folder verified.

In [2]:
import zipfile
import os

DATASET_ZIP = os.path.join(PROJECT_ROOT, "archive (1).zip")

print("📦 Dataset ZIP:", DATASET_ZIP)
print("📏 ZIP exists:", os.path.exists(DATASET_ZIP))

with zipfile.ZipFile(DATASET_ZIP, 'r') as zip_ref:
    files = zip_ref.namelist()

print("\n📂 ZIP contents:")
for file in files:
    print("   └──", file)

print("\n📊 Total files in ZIP:", len(files))

# Check expected Kaggle files
expected_files = {"Fake.csv", "True.csv"}
found_files = set(os.path.basename(f) for f in files)

print("\n🔍 Dataset verification:")
for file in expected_files:
    if file in found_files:
        print(f"   ✅ {file} found")
    else:
        print(f"   ❌ {file} NOT found")

if expected_files.issubset(found_files):
    print("\n✅ Real Fake & Real News dataset files verified.")
else:
    raise FileNotFoundError("❌ Expected Fake.csv / True.csv not found.")

📦 Dataset ZIP: /content/drive/MyDrive/NewsGuard/archive (1).zip
📏 ZIP exists: True

📂 ZIP contents:
   └── Fake.csv
   └── True.csv

📊 Total files in ZIP: 2

🔍 Dataset verification:
   ✅ Fake.csv found
   ✅ True.csv found

✅ Real Fake & Real News dataset files verified.

In [3]:
import zipfile
import os

# Create project directories
RAW_DIR = os.path.join(PROJECT_ROOT, "data", "raw")
os.makedirs(RAW_DIR, exist_ok=True)

# Extract the verified dataset
with zipfile.ZipFile(DATASET_ZIP, 'r') as zip_ref:
    zip_ref.extractall(RAW_DIR)

# Verify extracted files
print("📂 Raw data directory:")
for item in os.listdir(RAW_DIR):
    file_path = os.path.join(RAW_DIR, item)
    print(f"   └── {item} ({os.path.getsize(file_path) / (1024**2):.2f} MB)")

print("\n✅ Dataset extracted successfully.")

📂 Raw data directory:
   └── Fake.csv (59.88 MB)
   └── True.csv (51.10 MB)

✅ Dataset extracted successfully.

In [4]:
import pandas as pd
import os

FAKE_PATH = os.path.join(RAW_DIR, "Fake.csv")
TRUE_PATH = os.path.join(RAW_DIR, "True.csv")

# Load datasets
fake_df = pd.read_csv(FAKE_PATH)
true_df = pd.read_csv(TRUE_PATH)

print("📊 Fake News Dataset")
print("Shape:", fake_df.shape)
print("\nColumns:")
print(fake_df.columns.tolist())

print("\n" + "="*60)

print("\n📊 Real News Dataset")
print("Shape:", true_df.shape)
print("\nColumns:")
print(true_df.columns.tolist())

print("\n" + "="*60)

print("\n🔍 Fake Dataset Preview:")
display(fake_df.head())

print("\n🔍 Real Dataset Preview:")
display(true_df.head())

📊 Fake News Dataset
Shape: (23481, 4)

Columns:
['title', 'text', 'subject', 'date']

============================================================

📊 Real News Dataset
Shape: (21417, 4)

Columns:
['title', 'text', 'subject', 'date']

============================================================

🔍 Fake Dataset Preview:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

🔍 Real Dataset Preview:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
print("🔍 FAKE NEWS DATASET")
print("=" * 60)

print("\nMissing values:")
print(fake_df.isnull().sum())

print("\nDuplicate rows:", fake_df.duplicated().sum())


print("\n\n🔍 REAL NEWS DATASET")
print("=" * 60)

print("\nMissing values:")
print(true_df.isnull().sum())

print("\nDuplicate rows:", true_df.duplicated().sum())


print("\n\n📊 SUMMARY")
print("=" * 60)

print(f"Fake rows : {len(fake_df):,}")
print(f"Real rows : {len(true_df):,}")
print(f"Total rows: {len(fake_df) + len(true_df):,}")

🔍 FAKE NEWS DATASET
============================================================

Missing values:
title      0
text       0
subject    0
date       0
dtype: int64

Duplicate rows: 3


🔍 REAL NEWS DATASET
============================================================

Missing values:
title      0
text       0
subject    0
date       0
dtype: int64

Duplicate rows: 206


📊 SUMMARY
============================================================
Fake rows : 23,481
Real rows : 21,417
Total rows: 44,898

In [6]:
# Create labels
fake_df["label"] = 0
true_df["label"] = 1

# Combine both datasets
news_df = pd.concat(
    [fake_df, true_df],
    ignore_index=True
)

print("📊 Combined Dataset")
print("=" * 60)

print("Shape:", news_df.shape)

print("\nColumns:")
print(news_df.columns.tolist())

print("\nLabel distribution:")
print(news_df["label"].value_counts())

print("\nLabel percentage:")
print(news_df["label"].value_counts(normalize=True).mul(100).round(2))

print("\n🔹 Label Mapping:")
print("0 → Fake News")
print("1 → Real News")

print("\n🔍 Combined Dataset Preview:")
display(news_df.head())

📊 Combined Dataset
============================================================
Shape: (44898, 5)

Columns:
['title', 'text', 'subject', 'date', 'label']

Label distribution:
label
0    23481
1    21417
Name: count, dtype: int64

Label percentage:
label
0    52.3
1    47.7
Name: proportion, dtype: float64

🔹 Label Mapping:
0 → Fake News
1 → Real News

🔍 Combined Dataset Preview:

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [7]:
print("📊 SUBJECT DISTRIBUTION")
print("=" * 60)

print("\nOverall subject counts:")
print(news_df["subject"].value_counts())

print("\n\n📊 Subject distribution by label:")
subject_label = pd.crosstab(
    news_df["subject"],
    news_df["label"]
)

subject_label.columns = ["Fake", "Real"]

print(subject_label)

print("\n\n📈 Subject distribution (%):")
subject_percentage = pd.crosstab(
    news_df["subject"],
    news_df["label"],
    normalize="index"
).mul(100).round(2)

subject_percentage.columns = ["Fake %", "Real %"]

display(subject_percentage)

📊 SUBJECT DISTRIBUTION
============================================================

Overall subject counts:
subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64


📊 Subject distribution by label:
                 Fake   Real
subject
Government News  1570      0
Middle-east       778      0
News             9050      0
US_News           783      0
left-news        4459      0
politics         6841      0
politicsNews        0  11272
worldnews           0  10145


📈 Subject distribution (%):

                 Fake %  Real %
subject
Government News   100.0     0.0
Middle-east       100.0     0.0
News              100.0     0.0
US_News           100.0     0.0
left-news         100.0     0.0
politics          100.0     0.0
politicsNews        0.0   100.0
worldnews           0.0   100.0

In [8]:
# Keep only fields required for the NLP task
news_df = news_df[["title", "text", "label"]].copy()

# Combine title and article text
news_df["content"] = (
    news_df["title"].fillna("") + " " +
    news_df["text"].fillna("")
).str.strip()

# Remove rows with empty content
news_df = news_df[news_df["content"].str.len() > 0].copy()

# Reset index
news_df.reset_index(drop=True, inplace=True)

print("📊 FINAL NLP DATASET")
print("=" * 60)

print("Shape:", news_df.shape)

print("\nColumns:")
print(news_df.columns.tolist())

print("\nLabel distribution:")
print(news_df["label"].value_counts())

print("\nMissing values:")
print(news_df.isnull().sum())

print("\nEmpty content rows:", (news_df["content"].str.len() == 0).sum())

print("\n🔒 Leakage-prone columns removed:")
print("   ❌ subject")
print("   ❌ date")

print("\n✅ Final text feature: title + article text")

📊 FINAL NLP DATASET
============================================================
Shape: (44898, 4)

Columns:
['title', 'text', 'label', 'content']

Label distribution:
label
0    23481
1    21417
Name: count, dtype: int64

Missing values:
title      0
text       0
label      0
content    0
dtype: int64

Empty content rows: 0

🔒 Leakage-prone columns removed:
   ❌ subject
   ❌ date

✅ Final text feature: title + article text

In [9]:
print("🔍 DUPLICATE ANALYSIS")
print("=" * 60)

# Exact duplicate content
duplicate_content = news_df["content"].duplicated().sum()

# Duplicate content across the same/different labels
duplicate_groups = (
    news_df.groupby("content")["label"]
    .nunique()
)

conflicting_duplicates = (duplicate_groups > 1).sum()

print(f"Exact duplicate articles : {duplicate_content:,}")
print(f"Duplicate groups         : {(duplicate_groups > 1).sum():,}")
print(f"Conflicting-label groups : {conflicting_duplicates:,}")

print("\n📊 Duplicate content by label:")
print(
    news_df.groupby("label")["content"]
    .apply(lambda x: x.duplicated().sum())
)

print("\n🔎 Label mapping:")
print("0 → Fake News")
print("1 → Real News")

🔍 DUPLICATE ANALYSIS
============================================================
Exact duplicate articles : 5,795
Duplicate groups         : 0
Conflicting-label groups : 0

📊 Duplicate content by label:
label
0    5574
1     221
Name: content, dtype: int64

🔎 Label mapping:
0 → Fake News
1 → Real News

In [10]:
before_count = len(news_df)

# Remove exact duplicate articles
news_df = news_df.drop_duplicates(
    subset=["content"],
    keep="first"
).reset_index(drop=True)

after_count = len(news_df)
removed_count = before_count - after_count

print("🧹 DUPLICATE REMOVAL")
print("=" * 60)

print(f"Before removing duplicates : {before_count:,}")
print(f"Duplicates removed         : {removed_count:,}")
print(f"After removing duplicates  : {after_count:,}")

print("\n📊 Label distribution after deduplication:")
print(news_df["label"].value_counts())

print("\n📈 Label percentage:")
print(
    news_df["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\n🔍 Remaining duplicate content:")
print(news_df["content"].duplicated().sum())

print("\n✅ Deduplication completed.")

🧹 DUPLICATE REMOVAL
============================================================
Before removing duplicates : 44,898
Duplicates removed         : 5,795
After removing duplicates  : 39,103

📊 Label distribution after deduplication:
label
1    21196
0    17907
Name: count, dtype: int64

📈 Label percentage:
label
1    54.21
0    45.79
Name: proportion, dtype: float64

🔍 Remaining duplicate content:
0

✅ Deduplication completed.

In [11]:
# Calculate text length statistics
news_df["word_count"] = news_df["content"].str.split().str.len()
news_df["char_count"] = news_df["content"].str.len()

print("📊 ARTICLE LENGTH ANALYSIS")
print("=" * 60)

print("\nOverall word-count statistics:")
print(news_df["word_count"].describe().round(2))

print("\nOverall character-count statistics:")
print(news_df["char_count"].describe().round(2))

print("\n📈 Word count by label:")
display(
    news_df.groupby("label")["word_count"]
    .describe()
    .round(2)
)

print("\n📈 Character count by label:")
display(
    news_df.groupby("label")["char_count"]
    .describe()
    .round(2)
)

print("\n🔎 Label mapping:")
print("0 → Fake News")
print("1 → Real News")

📊 ARTICLE LENGTH ANALYSIS
============================================================

Overall word-count statistics:
count    39103.00
mean       410.45
std        315.09
min          2.00
25%        220.00
50%        378.00
75%        521.00
max       8148.00
Name: word_count, dtype: float64

Overall character-count statistics:
count    39103.00
mean      2504.62
std       1943.55
min         29.00
25%       1347.00
50%       2287.00
75%       3162.00
max      51893.00
Name: char_count, dtype: float64

📈 Word count by label:

         count    mean     std  min     25%    50%    75%     max
label
0      17907.0  428.94  357.01  2.0  279.00  385.0  514.0  8148.0
1      21196.0  394.83  273.77  4.0  157.75  368.5  533.0  5181.0

📈 Character count by label:

         count     mean      std   min      25%     50%     75%      max
label
0      17907.0  2577.48  2209.98  29.0  1668.50  2291.0  3073.0  51893.0
1      21196.0  2443.06  1683.56  30.0   972.75  2281.0  3291.0  29848.0

🔎 Label mapping:
0 → Fake News
1 → Real News

In [12]:
print("🔍 ARTICLE LENGTH QUALITY CHECK")
print("=" * 60)

# Very short articles
short_articles = news_df[news_df["word_count"] < 20]

print(f"\nArticles with < 20 words: {len(short_articles):,}")

print("\nLabel distribution among very short articles:")
print(short_articles["label"].value_counts())

# Long articles
long_articles = news_df[news_df["word_count"] > 2000]

print(f"\nArticles with > 2,000 words: {len(long_articles):,}")

print("\nLabel distribution among long articles:")
print(long_articles["label"].value_counts())

# Percentiles for detecting extreme lengths
print("\n📈 Word-count percentiles:")
for p in [90, 95, 99, 99.5]:
    print(f"{p}th percentile: {news_df['word_count'].quantile(p/100):.0f} words")

print("\n📌 Note:")
print("We will NOT remove length outliers blindly.")
print("They will be handled during preprocessing/modeling if required.")

🔍 ARTICLE LENGTH QUALITY CHECK
============================================================

Articles with < 20 words: 512

Label distribution among very short articles:
label
0    511
1      1
Name: count, dtype: int64

Articles with > 2,000 words: 128

Label distribution among long articles:
label
0    118
1     10
Name: count, dtype: int64

📈 Word-count percentiles:
90th percentile: 743 words
95th percentile: 890 words
99th percentile: 1320 words
99.5th percentile: 1674 words

📌 Note:
We will NOT remove length outliers blindly.
They will be handled during preprocessing/modeling if required.

In [13]:
# Create processed data directory
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data", "processed")
os.makedirs(PROCESSED_DIR, exist_ok=True)

# Save current cleaned dataset
CLEAN_DATA_PATH = os.path.join(
    PROCESSED_DIR,
    "news_cleaned.csv"
)

news_df.to_csv(CLEAN_DATA_PATH, index=False)

print("💾 CLEANED DATASET SAVED")
print("=" * 60)

print("File:", CLEAN_DATA_PATH)
print(f"Rows saved: {len(news_df):,}")
print(f"Columns saved: {news_df.shape[1]}")

print("\nColumns:")
print(news_df.columns.tolist())

print("\nFile size:")
print(f"{os.path.getsize(CLEAN_DATA_PATH) / (1024**2):.2f} MB")

print("\n✅ Cleaned dataset saved successfully.")

💾 CLEANED DATASET SAVED
============================================================
File: /content/drive/MyDrive/NewsGuard/data/processed/news_cleaned.csv
Rows saved: 39,103
Columns saved: 6

Columns:
['title', 'text', 'label', 'content', 'word_count', 'char_count']

File size:
188.27 MB

✅ Cleaned dataset saved successfully.

In [14]:
from sklearn.model_selection import train_test_split

# First split: 80% train, 20% temporary
train_df, temp_df = train_test_split(
    news_df,
    test_size=0.20,
    stratify=news_df["label"],
    random_state=42
)

# Second split: 10% validation, 10% test
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

# Reset indices
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print("📊 STRATIFIED DATA SPLIT")
print("=" * 60)

print(f"Total      : {len(news_df):,}")
print(f"Train      : {len(train_df):,}")
print(f"Validation : {len(val_df):,}")
print(f"Test       : {len(test_df):,}")

print("\n📈 Split percentages:")
print(f"Train      : {len(train_df)/len(news_df)*100:.2f}%")
print(f"Validation : {len(val_df)/len(news_df)*100:.2f}%")
print(f"Test       : {len(test_df)/len(news_df)*100:.2f}%")

print("\n🔍 Label distribution:")
print("\nTrain:")
print(train_df["label"].value_counts())

print("\nValidation:")
print(val_df["label"].value_counts())

print("\nTest:")
print(test_df["label"].value_counts())

print("\n📈 Label percentages:")
print("\nTrain:")
print(train_df["label"].value_counts(normalize=True).mul(100).round(2))

print("\nValidation:")
print(val_df["label"].value_counts(normalize=True).mul(100).round(2))

print("\nTest:")
print(test_df["label"].value_counts(normalize=True).mul(100).round(2))

print("\n✅ Stratified 80/10/10 split completed.")

📊 STRATIFIED DATA SPLIT
============================================================
Total      : 39,103
Train      : 31,282
Validation : 3,910
Test       : 3,911

📈 Split percentages:
Train      : 80.00%
Validation : 10.00%
Test       : 10.00%

🔍 Label distribution:

Train:
label
1    16957
0    14325
Name: count, dtype: int64

Validation:
label
1    2119
0    1791
Name: count, dtype: int64

Test:
label
1    2120
0    1791
Name: count, dtype: int64

📈 Label percentages:

Train:
label
1    54.21
0    45.79
Name: proportion, dtype: float64

Validation:
label
1    54.19
0    45.81
Name: proportion, dtype: float64

Test:
label
1    54.21
0    45.79
Name: proportion, dtype: float64

✅ Stratified 80/10/10 split completed.

In [15]:
print("🔒 SPLIT LEAKAGE CHECK")
print("=" * 60)

train_content = set(train_df["content"])
val_content = set(val_df["content"])
test_content = set(test_df["content"])

train_val_overlap = train_content.intersection(val_content)
train_test_overlap = train_content.intersection(test_content)
val_test_overlap = val_content.intersection(test_content)

print(f"Train ∩ Validation : {len(train_val_overlap):,}")
print(f"Train ∩ Test       : {len(train_test_overlap):,}")
print(f"Validation ∩ Test  : {len(val_test_overlap):,}")

total_overlap = (
    len(train_val_overlap)
    + len(train_test_overlap)
    + len(val_test_overlap)
)

print("\nTotal cross-split overlapping articles:", total_overlap)

if total_overlap == 0:
    print("\n✅ NO DATA LEAKAGE DETECTED")
    print("Train, validation and test sets are completely independent.")
else:
    print("\n❌ DATA LEAKAGE DETECTED")
    print("Overlapping articles found between splits.")

🔒 SPLIT LEAKAGE CHECK
============================================================
Train ∩ Validation : 0
Train ∩ Test       : 0
Validation ∩ Test  : 0

Total cross-split overlapping articles: 0

✅ NO DATA LEAKAGE DETECTED
Train, validation and test sets are completely independent.

In [16]:
# Create split directory
SPLIT_DIR = os.path.join(PROJECT_ROOT, "data", "splits")
os.makedirs(SPLIT_DIR, exist_ok=True)

# File paths
TRAIN_PATH = os.path.join(SPLIT_DIR, "train.csv")
VAL_PATH = os.path.join(SPLIT_DIR, "validation.csv")
TEST_PATH = os.path.join(SPLIT_DIR, "test.csv")

# Save splits
train_df.to_csv(TRAIN_PATH, index=False)
val_df.to_csv(VAL_PATH, index=False)
test_df.to_csv(TEST_PATH, index=False)

print("💾 DATA SPLITS SAVED")
print("=" * 60)

print(f"Train      → {TRAIN_PATH}")
print(f"Validation → {VAL_PATH}")
print(f"Test       → {TEST_PATH}")

print("\n📊 Saved row counts:")
print(f"Train      : {len(train_df):,}")
print(f"Validation : {len(val_df):,}")
print(f"Test       : {len(test_df):,}")

print("\n📁 Split directory contents:")
for file in os.listdir(SPLIT_DIR):
    file_path = os.path.join(SPLIT_DIR, file)
    print(f"   └── {file} ({os.path.getsize(file_path) / (1024**2):.2f} MB)")

print("\n✅ Train/validation/test splits saved successfully.")

💾 DATA SPLITS SAVED
============================================================
Train      → /content/drive/MyDrive/NewsGuard/data/splits/train.csv
Validation → /content/drive/MyDrive/NewsGuard/data/splits/validation.csv
Test       → /content/drive/MyDrive/NewsGuard/data/splits/test.csv

📊 Saved row counts:
Train      : 31,282
Validation : 3,910
Test       : 3,911

📁 Split directory contents:
   └── train.csv (150.67 MB)
   └── validation.csv (18.79 MB)
   └── test.csv (18.81 MB)

✅ Train/validation/test splits saved successfully.

In [17]:
print("🛡️ NEWSGUARD DAY 1 — FINAL INTEGRITY CHECK")
print("=" * 60)

# Verify saved files exist
required_files = [
    CLEAN_DATA_PATH,
    TRAIN_PATH,
    VAL_PATH,
    TEST_PATH
]

print("\n📁 Required files:")
for file_path in required_files:
    exists = os.path.exists(file_path)
    status = "✅" if exists else "❌"
    print(f"{status} {file_path}")

# Verify row counts
print("\n📊 Row count verification:")
print(f"Cleaned dataset : {len(news_df):,}")
print(f"Train           : {len(train_df):,}")
print(f"Validation      : {len(val_df):,}")
print(f"Test            : {len(test_df):,}")

# Verify split total
split_total = len(train_df) + len(val_df) + len(test_df)

print(f"\nSplit total     : {split_total:,}")
print(f"Original clean  : {len(news_df):,}")

# Verify labels
print("\n🏷️ Label verification:")
print("Expected labels: {0, 1}")
print("Actual labels  :", sorted(news_df["label"].unique().tolist()))

# Verify no duplicate content
print("\n🔍 Duplicate verification:")
print("Cleaned dataset duplicates:", news_df["content"].duplicated().sum())
print("Train duplicates           :", train_df["content"].duplicated().sum())
print("Validation duplicates      :", val_df["content"].duplicated().sum())
print("Test duplicates            :", test_df["content"].duplicated().sum())

# Final status
all_files_exist = all(os.path.exists(path) for path in required_files)
counts_match = split_total == len(news_df)
labels_valid = set(news_df["label"].unique()) == {0, 1}
no_duplicates = news_df["content"].duplicated().sum() == 0

print("\n" + "=" * 60)

if all_files_exist and counts_match and labels_valid and no_duplicates:
    print("🎉 DAY 1 DATASET INTEGRITY CHECK PASSED")
    print("✅ Dataset is ready for Day 2 preprocessing.")
else:
    print("❌ INTEGRITY CHECK FAILED")
    print("Please inspect the results above.")

🛡️ NEWSGUARD DAY 1 — FINAL INTEGRITY CHECK
============================================================

📁 Required files:
✅ /content/drive/MyDrive/NewsGuard/data/processed/news_cleaned.csv
✅ /content/drive/MyDrive/NewsGuard/data/splits/train.csv
✅ /content/drive/MyDrive/NewsGuard/data/splits/validation.csv
✅ /content/drive/MyDrive/NewsGuard/data/splits/test.csv

📊 Row count verification:
Cleaned dataset : 39,103
Train           : 31,282
Validation      : 3,910
Test            : 3,911

Split total     : 39,103
Original clean  : 39,103

🏷️ Label verification:
Expected labels: {0, 1}
Actual labels  : [0, 1]

🔍 Duplicate verification:
Cleaned dataset duplicates: 0
Train duplicates           : 0
Validation duplicates      : 0
Test duplicates            : 0

============================================================
🎉 DAY 1 DATASET INTEGRITY CHECK PASSED
✅ Dataset is ready for Day 2 preprocessing.